package etunote;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CreateImage.java
 *
 * Created on 10 mai 2011, 23:43:06
 */


/**
 *
 * @author mbayemoh
 */
public class AddImageView extends javax.swing.JFrame {

    /** Creates new form CreateImage */
    public AddImageView() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	this.setTitle("Ajout d'images");
        NameImageTextField = new javax.swing.JTextField();
        ParcourirImage = new javax.swing.JButton();
        ValidateImage = new javax.swing.JButton();
        CancelImage = new javax.swing.JButton();

        

        ParcourirImage.setForeground(new java.awt.Color(0, 0, 153));
        ParcourirImage.setText("Parcourir");
        ParcourirImage.setActionCommand("Parcourir");

        ValidateImage.setText("Valider");
        ValidateImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValidateImageActionPerformed(evt);
            }
        });

        CancelImage.setText("Annuler");
        CancelImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelImageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NameImageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(ParcourirImage, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ValidateImage)
                        .addGap(18, 18, 18)
                        .addComponent(CancelImage)))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameImageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ParcourirImage, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelImage)
                    .addComponent(ValidateImage))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ValidateImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValidateImageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ValidateImageActionPerformed

    private void CancelImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelImageActionPerformed
        // TODO add your handling code here:
    	this.setVisible(false);
    	setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    	
    }//GEN-LAST:event_CancelImageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new AddImageView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelImage;
    private javax.swing.JTextField NameImageTextField;
    private javax.swing.JButton ParcourirImage;
    private javax.swing.JButton ValidateImage;
    // End of variables declaration//GEN-END:variables
}
