/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddSemester.java
 *
 * Created on 11 mai 2011, 15:13:26
 */

package etunote;

import java.util.ArrayList;

/**
 *
 * @author mbayemoh
 */
public class AddSemesterView extends javax.swing.JFrame {

	private DisplayNoteView  parent;
    /** Creates new form AddSemester 
     * @param displayNoteView */
    public AddSemesterView(DisplayNoteView displayNoteView) {
    	this.parent = displayNoteView;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	this.setTitle("Ajouter un semestre");
        NameSemesterTextField = new javax.swing.JTextField();
        AddSemesterButton = new javax.swing.JButton();
        CancelSemesterButton = new javax.swing.JButton();
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        
        NameSemesterTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameSemesterTextFieldActionPerformed(evt);
            }
        });

        AddSemesterButton.setForeground(new java.awt.Color(0, 51, 204));
        AddSemesterButton.setText("Ajouter");
        AddSemesterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	AddSemesterButtonActionPerformed(evt);
            }
        });
        CancelSemesterButton.setForeground(new java.awt.Color(0, 51, 204));
        CancelSemesterButton.setText("Annuler");
        CancelSemesterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	CancelSemesterButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NameSemesterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AddSemesterButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CancelSemesterButton)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameSemesterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddSemesterButton)
                    .addComponent(CancelSemesterButton))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NameSemesterTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameSemesterTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameSemesterTextFieldActionPerformed

    
    private void AddSemesterButtonActionPerformed(java.awt.event.ActionEvent evt)
    {
    	Semester sem = new Semester(NameSemesterTextField.getText(), this.parent.getAppModel());
    	this.parent.getAppModel().addSemester(sem);
    	System.out.println("Semestre " + sem + " ajouté.");
    	this.parent.updateAppContent();
    	this.setVisible(false);
    	
    	
    }
    
    private void CancelSemesterButtonActionPerformed(java.awt.event.ActionEvent evt)
    {
    	this.setVisible(false);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddSemesterButton;
    private javax.swing.JButton CancelSemesterButton;
    private javax.swing.JTextField NameSemesterTextField;
    // End of variables declaration//GEN-END:variables

}
