/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DisplayNote.java
 *
 * Created on 5 mai 2011, 15:15:17
 */
package etunote;

import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;

import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.GroupLayout.Group;
import javax.swing.border.Border;
import javax.swing.border.TitledBorder;

/**
 *
 * @author mbayemoh
 */
public class DisplayNoteView extends javax.swing.JFrame {
	
	

    /** Creates new form DisplayNote */
    public DisplayNoteView(Application app) {
    	this.appModel = app;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SearchButton = new javax.swing.JButton();
        RechercheField = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        AddSemesterButton = new javax.swing.JButton();
        uvPanel = new javax.swing.JPanel();
        ViewByDate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SearchButton.setText("OK");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        RechercheField.setText("Recherche");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("SEMESTRES");

        AddSemesterButton.setFont(new java.awt.Font("Tahoma", 1, 14));
        AddSemesterButton.setForeground(new java.awt.Color(0, 0, 204));
        AddSemesterButton.setText("+");
        AddSemesterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddSemesterButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(AddSemesterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(uvPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 883, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(AddSemesterButton))
                .addGap(18, 18, 18)
                .addComponent(uvPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("NOTES", jPanel1);

        ViewByDate.setForeground(new java.awt.Color(0, 0, 204));
        ViewByDate.setText("Vue par date");
        ViewByDate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ViewByDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewByDateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 908, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ViewByDate, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RechercheField, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(SearchButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SearchButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(RechercheField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ViewByDate)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("NOTE");
        uvPanel = updateAppContent();
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void AddSemesterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddSemesterButtonActionPerformed
        // TODO add your handling code here:
    	new AddSemesterView(this).setVisible(true);
    	
    }//GEN-LAST:event_AddSemesterButtonActionPerformed
    
    private void AddUvButtonActionPerformed(Semester s) {//GEN-FIRST:event_AddSemesterButtonActionPerformed
        // TODO add your handling code here:
    	new AddUvView(s, this).setVisible(true);
    	
    }//GEN-LAST:event_AddSemesterButtonActionPerformed

    public Application getAppModel() {
		return appModel;
	}

	private void ViewByDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewByDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewByDateActionPerformed

    
    private Application appModel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddSemesterButton;
    private javax.swing.JPanel uvPanel;
    private javax.swing.JTextField RechercheField;
    private javax.swing.JButton SearchButton;
    private javax.swing.JButton ViewByDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
    
    public JPanel updateAppContent(){
    	uvPanel.removeAll();
    	GroupLayout uvPanelLayout;
    	uvPanelLayout=new javax.swing.GroupLayout(uvPanel);
        //javax.swing.GroupLayout notePanelLayout = new javax.swing.GroupLayout(notePanel);
    	uvPanel.setLayout(uvPanelLayout);
    	uvPanelLayout.setAutoCreateGaps(true);

        
    	Group parallelGroup = uvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING);
        Group verticalGroup = uvPanelLayout.createSequentialGroup();
        
        
        for (final Semester s : this.appModel.getSemesters()){
        	
        	JPanel semesterPan = new JPanel();
        	semesterPan.setName(s.getName());
        	TitledBorder title;
        	title = BorderFactory.createTitledBorder(s.getName());
        	semesterPan.setBorder(title);
        	
        	GroupLayout semPanelLayout;
        	semPanelLayout = new javax.swing.GroupLayout(semesterPan);
        	semesterPan.setLayout(semPanelLayout);
        	semPanelLayout.setAutoCreateGaps(true);
        	
        	Group semParallelGroup = semPanelLayout.createSequentialGroup();
            Group semVerticalGroup = semPanelLayout.createParallelGroup();
            
        	for (final Uv uv : s.getUvs()){
        		JButton uvButton = new JButton(uv.getName());
        		uvButton.setBackground(uv.getColorCode());
        		uvButton.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        showUv(uv);
                    }
                });
        		
        		semParallelGroup.addGroup(semPanelLayout.createParallelGroup()
                	.addGap(10, 10, 10)
                	.addComponent(uvButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE)
                	.addGap(10, 10, 10));
                	
          	
        		semVerticalGroup.addGroup(semPanelLayout.createParallelGroup()
                	.addGap(20, 20, 20)
                	.addComponent(uvButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE));
        	}
        	
        	JButton plusButton = new JButton(" + ");
        	plusButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    AddUvButtonActionPerformed(s);
                }
            });
    		semParallelGroup.addGroup(semPanelLayout.createParallelGroup()
            	.addGap(10, 10, 10)
            	.addComponent(plusButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE)
            	.addGap(10, 10, 10));
            	
      	
    		semVerticalGroup.addGroup(semPanelLayout.createParallelGroup()
            	.addGap(20, 20, 20)
            	.addComponent(plusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE));
        	
        	
        	semPanelLayout.setHorizontalGroup(semParallelGroup);
        	semPanelLayout.setVerticalGroup(semVerticalGroup);
        	
            parallelGroup.addGroup(uvPanelLayout.createSequentialGroup()
                	.addGap(10, 10, 10)
                	.addComponent(semesterPan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE)
                	.addGap(10, 10, 10));
                	
          	
            verticalGroup.addGroup(uvPanelLayout.createSequentialGroup()
                	.addGap(20, 20, 20)
                	.addComponent(semesterPan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE));
            	
            uvPanel.add(semesterPan);
        }
        
        uvPanelLayout.setHorizontalGroup(parallelGroup);
        uvPanelLayout.setVerticalGroup(verticalGroup);
        
    	
		return uvPanel;
    	
    }

	protected void showUv(Uv uv) {
		this.setVisible(false);
		UvView uvv = new UvView(uv);
		uvv.setVisible(true);
		
	}
}