package etunote;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PriseNote.java
 *
 * Created on 5 mai 2011, 13:37:25
 */


import java.awt.Color;
import java.awt.LayoutManager;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;

import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.TransferHandler;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeModel;
import javax.swing.JOptionPane;
/**
 *
 * @author mbayemoh
 */
public class PriseNoteView extends javax.swing.JFrame implements ActionListener {
	//TitleSpecificButton Title;
    /** Creates new form PriseNote */
	javax.swing.GroupLayout jPanel1Layout;
	JFileChooser fc = new JFileChooser();
	String file;
    public PriseNoteView() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	
    	DefaultTreeModel Model=new DefaultTreeModel(null);
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        BlocButton = new javax.swing.JButton();
        ParagraphButton = new javax.swing.JButton();
        TitleButton = new javax.swing.JButton();
        CodeButton = new javax.swing.JButton();
        DrawButton = new javax.swing.JButton();
        GrasButton = new javax.swing.JButton();
        SoulignButton = new javax.swing.JButton();
        ItalicButton = new javax.swing.JButton();
        SurlignButton = new javax.swing.JButton();
        ListeButton = new javax.swing.JButton();
        ImageButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        JMenuItem OpenItem = new javax.swing.JMenuItem();
        JMenuItem SaveItem= new javax.swing.JMenuItem();
        JMenuItem SaveAsItem= new javax.swing.JMenuItem();
        JMenuItem QuitItem= new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        JMenuItem UndoItem = new javax.swing.JMenuItem();
        JMenuItem RedoItem= new javax.swing.JMenuItem();
        JMenuItem CutItem = new javax.swing.JMenuItem();
        JMenuItem CopyItem = new javax.swing.JMenuItem();
        JMenuItem DeleteItem = new javax.swing.JMenuItem();
        


        
        
        this.setTitle("Prise de Note");
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setBackground(new java.awt.Color(0, 102, 102));
        jScrollPane1.setViewportView(jTree1);

        jTextField1.setText("Chapitre");
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setText("Cours");
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1Layout=new javax.swing.GroupLayout(jPanel1);
        JTextField jT=new JTextField();
        //javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)))
   
                  .addContainerGap(476, Short.MAX_VALUE))
           
                
        );
        
        
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(448, 448, 448))
               
        );

        jScrollPane2.setViewportView(jPanel1);

        jTabbedPane1.addTab("Note de Cours", jScrollPane2);
        
        
        
        //Title= new TitleSpecificButton();
        
       // Title.setBackground(Color.red);
        //Title.addMouseListener(new MouseAdapter(){
        //    public void mouseDragged(MouseEvent e){
        //      JButton button = (JButton)e.getSource();
        //       TransferHandler handle = button.getTransferHandler();
         //       handle.exportAsDrag(button, e, TransferHandler.COPY);
          //  				}
        //	});
        
        BlocButton.setFont(new java.awt.Font("Times New Roman", 0, 14));
        BlocButton.setText("+B");
        BlocButton.setBackground(Color.red);
        BlocButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlocButtonActionPerformed(evt);
            }
        });

        ParagraphButton.setFont(new java.awt.Font("Times New Roman", 0, 14));
        ParagraphButton.setText("+P");
        ParagraphButton.setBackground(Color.red);
        ParagraphButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParagraphButtonActionPerformed(evt);
            }
        });

        TitleButton.setFont(new java.awt.Font("Times New Roman", 0, 14));
        TitleButton.setText("+T");
        TitleButton.setBackground(Color.red);
        TitleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TitleButtonActionPerformed(evt);
            }
        });

        CodeButton.setFont(new java.awt.Font("Times New Roman", 0, 14));
        CodeButton.setText("+C");
        CodeButton.setBackground(Color.red);
        CodeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodeButtonActionPerformed(evt);
            }
        });

        DrawButton.setFont(new java.awt.Font("Times New Roman", 0, 14));
        DrawButton.setText("+D");
        DrawButton.setBackground(Color.red);
        DrawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DrawButtonActionPerformed(evt);
            }
        });

        GrasButton.setFont(new java.awt.Font("Times New Roman", 0, 14));
        GrasButton.setText("G");
        GrasButton.setBackground(Color.yellow);
        GrasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GrasButtonActionPerformed(evt);
            }
        });

        SoulignButton.setFont(new java.awt.Font("Times New Roman", 0, 14));
        SoulignButton.setText("S");
        SoulignButton.setBackground(Color.yellow);
        SoulignButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoulignButtonActionPerformed(evt);
            }
        });

        ItalicButton.setFont(new java.awt.Font("Times New Roman", 0, 14));
        ItalicButton.setText("I");
        ItalicButton.setBackground(Color.yellow);
        ItalicButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItalicButtonActionPerformed(evt);
            }
        });

        SurlignButton.setFont(new java.awt.Font("Times New Roman", 0, 12));
        SurlignButton.setText("Surlign");
        SurlignButton.setBackground(Color.gray);
        SurlignButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SurlignButtonActionPerformed(evt);
            }
        });

        ListeButton.setFont(new java.awt.Font("Times New Roman", 0, 12));
        ListeButton.setText("Liste");
        ListeButton.setBackground(Color.gray);
        ListeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListeButtonActionPerformed(evt);
            }
        });

        ImageButton.setFont(new java.awt.Font("Times New Roman", 0, 14));
        ImageButton.setText("+I");
        ImageButton.setBackground(Color.red);
        ImageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImageButtonActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        OpenItem.setText("Open");
        OpenItem.addActionListener(new java.awt.event.ActionListener()
        {
        	 public void actionPerformed(java.awt.event.ActionEvent evt) {
        		 OpenItemActionPerformed(evt);}
        });
        
        jMenu1.add(OpenItem);

        SaveItem.setText("Save");
        SaveItem.addActionListener(new java.awt.event.ActionListener()
        {
        	 public void actionPerformed(java.awt.event.ActionEvent evt) {
        		 SaveItemActionPerformed(evt);}
        });
        
        jMenu1.add(SaveItem);

        SaveAsItem.setText("Save as");
        SaveAsItem.addActionListener(new java.awt.event.ActionListener()
        {
        	 public void actionPerformed(java.awt.event.ActionEvent evt) {
        		 SaveAsItemActionPerformed(evt);}
        });
        jMenu1.add(SaveAsItem);

        QuitItem.setText("Quit");
        QuitItem.addActionListener(new java.awt.event.ActionListener()
        {
        	 public void actionPerformed(java.awt.event.ActionEvent evt) {
        		 QuitItemActionPerformed(evt);}
        });
        jMenu1.add(QuitItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        UndoItem.setText("Undo");
        UndoItem.addActionListener(new java.awt.event.ActionListener()
        {
        	 public void actionPerformed(java.awt.event.ActionEvent evt) {
        		 UndoItemActionPerformed(evt);}
        });
        jMenu2.add(UndoItem);

        RedoItem.setText("Redo");
        RedoItem.addActionListener(new java.awt.event.ActionListener()
        {
        	 public void actionPerformed(java.awt.event.ActionEvent evt) {
        		 RedoItemActionPerformed(evt);}
        });
        jMenu2.add(RedoItem);

        CutItem.setText("Cut");
        CutItem.addActionListener(new java.awt.event.ActionListener()
        {
        	 public void actionPerformed(java.awt.event.ActionEvent evt) {
        		 CutItemActionPerformed(evt);}
        });
        jMenu2.add(CutItem);

        CopyItem.setText("Copy");
        CopyItem.addActionListener(new java.awt.event.ActionListener()
        {
        	 public void actionPerformed(java.awt.event.ActionEvent evt) {
        		 CopyItemActionPerformed(evt);}
        });
        jMenu2.add(CopyItem);

        DeleteItem.setText("Delete");
        DeleteItem.addActionListener(new java.awt.event.ActionListener()
        {
        	 public void actionPerformed(java.awt.event.ActionEvent evt) {
        		 DeleteItemActionPerformed(evt);}
        });
        jMenu2.add(DeleteItem);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                	//.addComponent(Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BlocButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ParagraphButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TitleButton, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                    .addComponent(GrasButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DrawButton, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(ListeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ItalicButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SoulignButton, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                    .addComponent(SurlignButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ImageButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CodeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                //.addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(TitleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(ParagraphButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BlocButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ImageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CodeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DrawButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(GrasButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SoulignButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ItalicButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SurlignButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ListeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTabbedPane1, 0, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        //this.jPanel1.add(jtextfield);
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ImageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImageButtonActionPerformed
        // TODO add your handling code here:
    	new CreateImageView().setVisible(true);
    }//GEN-LAST:event_ImageButtonActionPerformed

    private void CodeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodeButtonActionPerformed

    private void DrawButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DrawButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DrawButtonActionPerformed

    private void GrasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GrasButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GrasButtonActionPerformed

    private void SoulignButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoulignButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SoulignButtonActionPerformed

    private void ItalicButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItalicButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItalicButtonActionPerformed

    private void SurlignButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SurlignButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SurlignButtonActionPerformed

    private void ListeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ListeButtonActionPerformed

    private void TitleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TitleButtonActionPerformed
        // TODO add your handling code here:
    	System.out.print("ca marche ");
    	jPanel1.add(new JTextField(50));
    	jPanel1.revalidate();
    	jPanel1.repaint();
    	System.out.print(jPanel1.countComponents());
    	
    }//GEN-LAST:event_TitleButtonActionPerformed

    private void ParagraphButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParagraphButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ParagraphButtonActionPerformed

    private void BlocButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlocButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BlocButtonActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void OpenItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    	fc.setCurrentDirectory(new File("."));
		int returnVal = fc.showOpenDialog(this);
		if (returnVal == JFileChooser.APPROVE_OPTION) {
			try{
			file = fc.getSelectedFile().getAbsolutePath();
			}
			catch(Exception e)
			{
				JOptionPane.showMessageDialog(this, 
						"Probleme fichier",
						"Erreur",
						JOptionPane.ERROR_MESSAGE);
			}
			
		}

    }//GEN-LAST:event_jTextField2ActionPerformed
    
    private void SaveItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed
    
    private void SaveAsItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed
    
    private void QuitItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    	System.exit(0);
    
    }//GEN-LAST:event_jTextField2ActionPerformed
    
    private void UndoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed
    
    private void RedoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed
    
    private void CutItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed
    
    private void CopyItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed
    
    private void DeleteItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new PriseNoteView().setVisible(true);
            	//new DisplayNoteView().setVisible(true);

            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BlocButton;
    private javax.swing.JButton CodeButton;
    private javax.swing.JButton DrawButton;
    private javax.swing.JButton GrasButton;
    private javax.swing.JButton ImageButton;
    private javax.swing.JButton ItalicButton;
    private javax.swing.JButton ListeButton;
    private javax.swing.JButton ParagraphButton;
    private javax.swing.JButton SoulignButton;
    private javax.swing.JButton SurlignButton;
    private javax.swing.JButton TitleButton;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem OpenItem;
    private javax.swing.JMenuItem SaveItem;
    private javax.swing.JMenuItem SaveAsItem;
    private javax.swing.JMenuItem QuitItem;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
	@Override
	public void actionPerformed(ActionEvent e) {
		// TODO Auto-generated method stub
		
	}
}
