package etunote;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PriseNote.java
 *
 * Created on 5 mai 2011, 13:37:25
 */


import java.awt.Color;
import java.awt.Event;
import java.awt.LayoutManager;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.util.ArrayList;

import javax.swing.GroupLayout.Group;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.TransferHandler;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeModel;
import javax.swing.JOptionPane;
/**
 *
 * @author mbayemoh
 */
public class PriseNoteView extends javax.swing.JFrame implements ActionListener {
	//TitleSpecificButton Title;
    /** Creates new form PriseNote */
	
	Note noteModel;
	javax.swing.GroupLayout notePanelLayout;
	JFileChooser fc = new JFileChooser();
	String file;
	
	
    public PriseNoteView(Note model) {
    	this.noteModel = model;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	
    	DefaultTreeModel Model=new DefaultTreeModel(null);
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        notePanel = new javax.swing.JPanel();
        fields = new ArrayList<JTextField>();
        BlocButton = new javax.swing.JButton();
        ParagraphButton = new javax.swing.JButton();
        TitleButton = new javax.swing.JButton();
        CodeButton = new javax.swing.JButton();
        DrawButton = new javax.swing.JButton();
        GrasButton = new javax.swing.JButton();
        SoulignButton = new javax.swing.JButton();
        ItalicButton = new javax.swing.JButton();
        SurlignButton = new javax.swing.JButton();
        ListeButton = new javax.swing.JButton();
        ImageButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        JMenuItem OpenItem = new javax.swing.JMenuItem();
        JMenuItem SaveItem= new javax.swing.JMenuItem();
        JMenuItem SaveAsItem= new javax.swing.JMenuItem();
        JMenuItem QuitItem= new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        JMenuItem UndoItem = new javax.swing.JMenuItem();
        JMenuItem RedoItem= new javax.swing.JMenuItem();
        JMenuItem CutItem = new javax.swing.JMenuItem();
        JMenuItem CopyItem = new javax.swing.JMenuItem();
        JMenuItem DeleteItem = new javax.swing.JMenuItem();
        


        
        
        this.setTitle("Prise de Note");
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setBackground(new java.awt.Color(0, 102, 102));
        jScrollPane1.setViewportView(jTree1);

        
        //SHOW THE CONTENT OF THE NOTE
        notePanel = updateNoteContent();
        
        jScrollPane2.setViewportView(notePanel);

        jTabbedPane1.addTab("Note de Cours", jScrollPane2);
        
        
        
        //Title= new TitleSpecificButton();
        
       // Title.setBackground(Color.red);
        //Title.addMouseListener(new MouseAdapter(){
        //    public void mouseDragged(MouseEvent e){
        //      JButton button = (JButton)e.getSource();
        //       TransferHandler handle = button.getTransferHandler();
         //       handle.exportAsDrag(button, e, TransferHandler.COPY);
          //  				}
        //	});
        
        BlocButton.setFont(new java.awt.Font("Times New Roman", 0, 14));
        BlocButton.setText("+B");
        BlocButton.setBackground(Color.red);
        BlocButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlocButtonActionPerformed(evt);
            }
        });

        ParagraphButton.setFont(new java.awt.Font("Times New Roman", 0, 14));
        ParagraphButton.setText("+P");
        ParagraphButton.setBackground(Color.red);
        ParagraphButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParagraphButtonActionPerformed(evt);
            }
        });

        TitleButton.setFont(new java.awt.Font("Times New Roman", 0, 14));
        TitleButton.setText("+T");
        TitleButton.setBackground(Color.red);
        TitleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TitleButtonActionPerformed(evt);
            }
        });

        CodeButton.setFont(new java.awt.Font("Times New Roman", 0, 14));
        CodeButton.setText("+C");
        CodeButton.setBackground(Color.red);
        CodeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodeButtonActionPerformed(evt);
            }
        });

        DrawButton.setFont(new java.awt.Font("Times New Roman", 0, 14));
        DrawButton.setText("+D");
        DrawButton.setBackground(Color.red);
        DrawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DrawButtonActionPerformed(evt);
            }
        });

        GrasButton.setFont(new java.awt.Font("Times New Roman", 0, 14));
        GrasButton.setText("G");
        GrasButton.setBackground(Color.yellow);
        GrasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GrasButtonActionPerformed(evt);
            }
        });

        SoulignButton.setFont(new java.awt.Font("Times New Roman", 0, 14));
        SoulignButton.setText("S");
        SoulignButton.setBackground(Color.yellow);
        SoulignButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoulignButtonActionPerformed(evt);
            }
        });

        ItalicButton.setFont(new java.awt.Font("Times New Roman", 0, 14));
        ItalicButton.setText("I");
        ItalicButton.setBackground(Color.yellow);
        ItalicButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItalicButtonActionPerformed(evt);
            }
        });

        SurlignButton.setFont(new java.awt.Font("Times New Roman", 0, 12));
        SurlignButton.setText("Surlign");
        SurlignButton.setBackground(Color.gray);
        SurlignButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SurlignButtonActionPerformed(evt);
            }
        });

        ListeButton.setFont(new java.awt.Font("Times New Roman", 0, 12));
        ListeButton.setText("Liste");
        ListeButton.setBackground(Color.gray);
        ListeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListeButtonActionPerformed(evt);
            }
        });

        ImageButton.setFont(new java.awt.Font("Times New Roman", 0, 14));
        ImageButton.setText("+I");
        ImageButton.setBackground(Color.red);
        ImageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImageButtonActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        OpenItem.setText("Open");
        OpenItem.addActionListener(new java.awt.event.ActionListener()
        {
        	 public void actionPerformed(java.awt.event.ActionEvent evt) {
        		 OpenItemActionPerformed(evt);}
        });
        
        jMenu1.add(OpenItem);

        SaveItem.setText("Save");
        SaveItem.addActionListener(new java.awt.event.ActionListener()
        {
        	 public void actionPerformed(java.awt.event.ActionEvent evt) {
        		 SaveItemActionPerformed(evt);}
        });
        
        jMenu1.add(SaveItem);

        SaveAsItem.setText("Save as");
        SaveAsItem.addActionListener(new java.awt.event.ActionListener()
        {
        	 public void actionPerformed(java.awt.event.ActionEvent evt) {
        		 SaveAsItemActionPerformed(evt);}
        });
        jMenu1.add(SaveAsItem);

        QuitItem.setText("Quit");
        QuitItem.addActionListener(new java.awt.event.ActionListener()
        {
        	 public void actionPerformed(java.awt.event.ActionEvent evt) {
        		 QuitItemActionPerformed(evt);}
        });
        jMenu1.add(QuitItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        UndoItem.setText("Undo");
        UndoItem.addActionListener(new java.awt.event.ActionListener()
        {
        	 public void actionPerformed(java.awt.event.ActionEvent evt) {
        		 UndoItemActionPerformed(evt);}
        });
        jMenu2.add(UndoItem);

        RedoItem.setText("Redo");
        RedoItem.addActionListener(new java.awt.event.ActionListener()
        {
        	 public void actionPerformed(java.awt.event.ActionEvent evt) {
        		 RedoItemActionPerformed(evt);}
        });
        jMenu2.add(RedoItem);

        CutItem.setText("Cut");
        CutItem.addActionListener(new java.awt.event.ActionListener()
        {
        	 public void actionPerformed(java.awt.event.ActionEvent evt) {
        		 CutItemActionPerformed(evt);}
        });
        jMenu2.add(CutItem);

        CopyItem.setText("Copy");
        CopyItem.addActionListener(new java.awt.event.ActionListener()
        {
        	 public void actionPerformed(java.awt.event.ActionEvent evt) {
        		 CopyItemActionPerformed(evt);}
        });
        jMenu2.add(CopyItem);

        DeleteItem.setText("Delete");
        DeleteItem.addActionListener(new java.awt.event.ActionListener()
        {
        	 public void actionPerformed(java.awt.event.ActionEvent evt) {
        		 DeleteItemActionPerformed(evt);}
        });
        jMenu2.add(DeleteItem);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                	//.addComponent(Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BlocButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ParagraphButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TitleButton, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                    .addComponent(GrasButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DrawButton, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(ListeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ItalicButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SoulignButton, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                    .addComponent(SurlignButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ImageButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CodeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                //.addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(TitleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(ParagraphButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BlocButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ImageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CodeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DrawButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(GrasButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SoulignButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ItalicButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SurlignButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ListeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTabbedPane1, 0, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        //this.notePanel.add(jtextfield);
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ImageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImageButtonActionPerformed
        // TODO add your handling code here:
    	new AddImageView().setVisible(true);
    }//GEN-LAST:event_ImageButtonActionPerformed

    private void CodeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodeButtonActionPerformed

    private void DrawButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DrawButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DrawButtonActionPerformed

    private void GrasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GrasButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GrasButtonActionPerformed

    private void SoulignButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoulignButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SoulignButtonActionPerformed

    private void ItalicButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItalicButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItalicButtonActionPerformed

    private void SurlignButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SurlignButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SurlignButtonActionPerformed

    private void ListeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ListeButtonActionPerformed

    private void TitleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TitleButtonActionPerformed
        // TODO add your handling code here:
    	System.out.println("Ajout d'un titre");
    	Title title = new Title(this.noteModel.getLastPosition() + 1, this.noteModel.getLastTitleLevel());
    	this.noteModel.addContent(title);
    	notePanel = updateNoteContent();
    	
    }//GEN-LAST:event_TitleButtonActionPerformed

    private void ParagraphButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParagraphButtonActionPerformed
    	System.out.println("Ajout d'un paragraph");
    	Paragraph p = new Paragraph(this.noteModel.getLastPosition() + 1);
    	this.noteModel.addContent(p);
    	notePanel = updateNoteContent();
    }//GEN-LAST:event_ParagraphButtonActionPerformed

    private void BlocButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlocButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BlocButtonActionPerformed

    private void OpenItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    	fc.setCurrentDirectory(new File("."));
		int returnVal = fc.showOpenDialog(this);
		if (returnVal == JFileChooser.APPROVE_OPTION) {
			try{
			file = fc.getSelectedFile().getAbsolutePath();
			}
			catch(Exception e)
			{
				JOptionPane.showMessageDialog(this, 
						"Probleme fichier",
						"Erreur",
						JOptionPane.ERROR_MESSAGE);
			}
			
		}

    }//GEN-LAST:event_jTextField2ActionPerformed
    
    private void SaveItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed
    
    private void SaveAsItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed
    
    private void QuitItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    	System.exit(0);
    
    }//GEN-LAST:event_jTextField2ActionPerformed
    
    private void UndoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed
    
    private void RedoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed
    
    private void CutItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed
    
    private void CopyItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed
    
    private void DeleteItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed
    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BlocButton;
    private javax.swing.JButton CodeButton;
    private javax.swing.JButton DrawButton;
    private javax.swing.JButton GrasButton;
    private javax.swing.JButton ImageButton;
    private javax.swing.JButton ItalicButton;
    private javax.swing.JButton ListeButton;
    private javax.swing.JButton ParagraphButton;
    private javax.swing.JButton SoulignButton;
    private javax.swing.JButton SurlignButton;
    private javax.swing.JButton TitleButton;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem OpenItem;
    private javax.swing.JMenuItem SaveItem;
    private javax.swing.JMenuItem SaveAsItem;
    private javax.swing.JMenuItem QuitItem;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel notePanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
    
    private ArrayList<JTextField> fields;
    
    
	@Override
	public void actionPerformed(ActionEvent e) {
		// TODO Auto-generated method stub
		
	}
	
	public JPanel updateNoteContent(){
		notePanel.removeAll();
        notePanelLayout=new javax.swing.GroupLayout(notePanel);
        //javax.swing.GroupLayout notePanelLayout = new javax.swing.GroupLayout(notePanel);
        notePanel.setLayout(notePanelLayout);
        notePanelLayout.setAutoCreateGaps(true);

        Group parallelGroup = notePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING);
        Group verticalGroup = notePanelLayout.createSequentialGroup();
        
        
        
        for (final Content c : this.noteModel.getContents()){
        	if(c instanceof Title){
        		final JTextField f = new JTextField();
        		f.setText(((Title) c).getName());
        		f.addKeyListener(new KeyListener() {
					
					@Override
					public void keyTyped(KeyEvent arg0) {
						// TODO Auto-generated method stub
						
					}
					
					@Override
					public void keyReleased(KeyEvent arg0) {
						saveTitle(f, (Title) c);
						
					}
					
					@Override
					public void keyPressed(KeyEvent arg0) {
						// TODO Auto-generated method stub
						
					}
				});
        		if(((Title) c).getLevel() == 1){
                    parallelGroup.addGroup(notePanelLayout.createSequentialGroup()
                    	.addGap(5, 5, 5)
                    	.addComponent(f, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE));
                    	
              	
                    verticalGroup.addGroup(notePanelLayout.createParallelGroup()
                    	.addGap(20, 20, 20)
                    	.addComponent(f, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE));
        		}
        		else{
        		JButton levelDown = new JButton("<");
        		levelDown.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                    	downTitleLevel((Title) c);
                        
                    }
                });
        		
        		JButton levelUp = new JButton(">");
        		levelUp.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        upTitleLevel((Title) c);
                    }
                });
                f.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                int indent = ((Title) c).getLevel() * 20;
                parallelGroup.addGroup(notePanelLayout.createSequentialGroup()
                	.addGap(indent, indent, indent)
                	.addComponent(levelDown)
                	.addComponent(f, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                	.addComponent(levelUp));
                	
          	
                verticalGroup.addGroup(notePanelLayout.createParallelGroup()
                	.addGap(20, 20, 20)
                	.addComponent(levelDown)
                	.addComponent(f, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                	.addComponent(levelUp));
                
        		}   	
        	}
        	
        	else if(c instanceof Paragraph){
        		final JTextArea textArea = new JTextArea();
        		textArea.setText(((Paragraph) c).getText());
        		textArea.addKeyListener(new KeyListener() {
					
					@Override
					public void keyTyped(KeyEvent arg0) {
						// TODO Auto-generated method stub
						
					}
					
					@Override
					public void keyReleased(KeyEvent arg0) {
						saveParagraph(textArea, (Paragraph) c);
						
					}
					
					@Override
					public void keyPressed(KeyEvent arg0) {
						// TODO Auto-generated method stub
						
					}
				});
//        		textArea.firePropertyChange(arg0, arg1, arg2);
        		textArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                parallelGroup.addGroup(notePanelLayout.createSequentialGroup()
                	.addGap(10, 10, 10)
                	.addComponent(textArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE)
                	.addGap(10, 10, 10));
                	
          	
                verticalGroup.addGroup(notePanelLayout.createSequentialGroup()
                	.addGap(20, 20, 20)
                	.addComponent(textArea, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE));
                	
        	}
        }
        
        
        notePanelLayout.setHorizontalGroup(parallelGroup);
        notePanelLayout.setVerticalGroup(verticalGroup);
        
		return notePanel;

	}

	protected void saveParagraph(JTextArea textArea, Paragraph p) {
		p.setText(textArea.getText());
		
	}

	protected void saveTitle(JTextField f, Title t) {
		t.setName(f.getText());
	}

	protected void downTitleLevel(Title c) {
		c.levelDown();
		this.noteModel.downLastTitleLevel();
        notePanel = updateNoteContent();
		
	}
	
	protected void upTitleLevel(Title c) {
		c.levelUp();
		this.noteModel.upLastTitleLevel();
        notePanel = updateNoteContent();
		
	}
}
