/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UvView.java
 *
 * Created on 17 mai 2011, 16:48:28
 */
package etunote;

import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.GroupLayout.Group;
import javax.swing.border.TitledBorder;

/**
 *
 * @author mbayemoh
 */
public class UvView extends PanelView {

	private MainView mainView;
	
    /** Creates new form UvView */
    public UvView(MainView mainView, Uv uvModel) {
    	this.mainView = mainView;
    	this.uvModel = uvModel;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        OpenItem = new javax.swing.JMenuItem();
        SaveItem = new javax.swing.JMenuItem();
        SaveAsItem = new javax.swing.JMenuItem();
        QuitItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        UndoItem = new javax.swing.JMenuItem();
        RedoItem = new javax.swing.JMenuItem();
        CutItem = new javax.swing.JMenuItem();
        CopyItem = new javax.swing.JMenuItem();
        DeleteItem = new javax.swing.JMenuItem();
        uvPanel =  new javax.swing.JPanel();
         
        
        //setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
       
        jTabbedPane1.addTab("NOTES", jScrollPane1);

        jMenu1.setText("File");

        OpenItem.setText("Open");
        OpenItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenItemActionPerformed(evt);
            }
        });
        jMenu1.add(OpenItem);

        SaveItem.setText("Save");
        SaveItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveItemActionPerformed(evt);
            }
        });
        jMenu1.add(SaveItem);

        SaveAsItem.setText("Save as");
        SaveAsItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveAsItemActionPerformed(evt);
            }
        });
        jMenu1.add(SaveAsItem);

        QuitItem.setText("Quit");
        QuitItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitItemActionPerformed(evt);
            }
        });
        jMenu1.add(QuitItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        UndoItem.setText("Undo");
        UndoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UndoItemActionPerformed(evt);
            }
        });
        jMenu2.add(UndoItem);

        RedoItem.setText("Redo");
        RedoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RedoItemActionPerformed(evt);
            }
        });
        jMenu2.add(RedoItem);

        CutItem.setText("Cut");
        CutItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CutItemActionPerformed(evt);
            }
        });
        jMenu2.add(CutItem);

        CopyItem.setText("Copy");
        CopyItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CopyItemActionPerformed(evt);
            }
        });
        jMenu2.add(CopyItem);

        DeleteItem.setText("Delete");
        DeleteItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteItemActionPerformed(evt);
            }
        });
        jMenu2.add(DeleteItem);

        jMenuBar1.add(jMenu2);

        //setJMenuBar(jMenuBar1);
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        //getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(uvPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(uvPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                .addContainerGap())
        );

        this.updateContent();
    }
    
    private void OpenItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenItemActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_OpenItemActionPerformed

    private void SaveItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveItemActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_SaveItemActionPerformed

    private void SaveAsItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveAsItemActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_SaveAsItemActionPerformed

    private void QuitItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitItemActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_QuitItemActionPerformed

    private void UndoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UndoItemActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_UndoItemActionPerformed

    private void RedoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RedoItemActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_RedoItemActionPerformed

    private void CutItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CutItemActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_CutItemActionPerformed

    private void CopyItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CopyItemActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_CopyItemActionPerformed

    private void DeleteItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteItemActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_DeleteItemActionPerformed
    
    private void showAddNoteDialog() {
    		String s = (String)JOptionPane.showInputDialog(
    		                    this.mainView,
    		                    "Entrez le nom de la note",
    		                    "Ajouter une note",
    		                    JOptionPane.PLAIN_MESSAGE);

    		//If a string was returned, add the semester
    		if ((s != null) && (s.length() > 0)) {
    			Note note = new Note(s, uvModel);
    	    	updateContent();
    		}

    }

    public Uv getUvModel() {
		return uvModel;
	}

	public void setUvModel(Uv uvModel) {
		this.uvModel = uvModel;
	}

	private Uv uvModel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CopyItem;
    private javax.swing.JMenuItem CutItem;
    private javax.swing.JMenuItem DeleteItem;
    private javax.swing.JMenuItem OpenItem;
    private javax.swing.JMenuItem QuitItem;
    private javax.swing.JMenuItem RedoItem;
    private javax.swing.JMenuItem SaveAsItem;
    private javax.swing.JMenuItem SaveItem;
    private javax.swing.JMenuItem UndoItem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel uvPanel;
    // End of variables declaration//GEN-END:variables
    
    public void updateContent(){
    	uvPanel.removeAll();
    	GroupLayout uvPanelLayout;
    	uvPanelLayout=new javax.swing.GroupLayout(uvPanel);
        //javax.swing.GroupLayout notePanelLayout = new javax.swing.GroupLayout(notePanel);
    	uvPanel.setLayout(uvPanelLayout);
    	uvPanelLayout.setAutoCreateGaps(true);

        
    	Group parallelGroup = uvPanelLayout.createSequentialGroup();
        Group verticalGroup = uvPanelLayout.createParallelGroup();
        
        
        for (final Note note : this.uvModel.getNotes()){
            
    		JButton uvButton = new JButton(note.getName());
    		uvButton.setBackground(note.getColorCode());
    		uvButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                	mainView.showNote(note);
                }
            });
    		parallelGroup.addGroup(uvPanelLayout.createParallelGroup()
            	.addGap(10, 10, 10)
            	.addComponent(uvButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE)
            	.addGap(10, 10, 10));
            	
      	
    		verticalGroup.addGroup(uvPanelLayout.createParallelGroup()
            	.addGap(20, 20, 20)
            	.addComponent(uvButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE));
        }
        	
        	JButton plusButton = new JButton(" + ");
        	plusButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    showAddNoteDialog();
                }
            });
        	parallelGroup.addGroup(uvPanelLayout.createParallelGroup()
            	.addGap(10, 10, 10)
            	.addComponent(plusButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE)
            	.addGap(10, 10, 10));
            	
      	
        	verticalGroup.addGroup(uvPanelLayout.createParallelGroup()
            	.addGap(20, 20, 20)
            	.addComponent(plusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE));
        	
        	
        uvPanelLayout.setHorizontalGroup(parallelGroup);
        uvPanelLayout.setVerticalGroup(verticalGroup);
    	
    }
}
